services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build: ./django-project
    container_name: hotel_search
    command: uv run python manage.py runserver 127.0.0.1:8000 #0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hotel_search.settings
      - PYTHONUNBUFFERED=1
      - FASTAPI_URL=http://127.0.0.1:8001
    depends_on:
      - db
      - fastapi

  fastapi:
    build: ./fastapi-scraper
    container_name: fastapi_scraper
    volumes:
      - ./fastapi_scraper:/app
    ports:
      - "8001:8001"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker: # async workload queue for offloading
    build: ./fastapi_scraper
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
      - fastapi
    volumes:
      - .:/app

volumes:
  postgres_data:
