version: '3.9'

services:
  web:
    build: ./django_project
    container_name: hotel_search
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_URL=http://fastapi:8001
    depends_on:
      - fastapi

  fastapi:
    build: ./fastapi_service
    container_name: fastapi_service
    volumes:
      - ./fastapi_service:/app
    ports:
      - "8001:8001"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
