[project]
name = "fastapi-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "playwright>=1.53.0",
    "scrapy>=2.13.3",
    "uvicorn>=0.35.0",
]
